# Generated by Django 3.2.8 on 2021-10-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='en_title',
        ),
        migrations.AddField(
            model_name='news',
            name='ru_title',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
