# Generated by Django 3.2.8 on 2021-10-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='displacement',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_load',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='passengers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
