# Generated by Django 3.2.8 on 2021-10-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211015_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='spec',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
