# Generated by Django 3.2.8 on 2021-10-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='en_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='en_name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='en_spec',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
