# Generated by Django 3.2.8 on 2021-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211022_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='into_photos',
            field=models.JSONField(null=True),
        ),
    ]
